server:
  name: "menu-api"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "C:\\go\\menu\\project_ws\\logs\\debug\\menu-debug.log"
  infoFileName: "C:\\go\\menu\\project_ws\\logs\\info\\menu-info.log"
  warnFileName: "C:\\go\\menu\\project_ws\\logs\\error\\menu-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"